events/urls.py
from django.urls import path

from events.views import EventDetailView, CreateEventIdeaView, UpvoteIdeaView

app_name = "events"
urlpatterns = [
    path("<int:event_id>/", EventDetailView.as_view(), name="event-detail"),
    path("<int:event_id>/ideas/", CreateEventIdeaView.as_view(), name="create-idea"),
    path("<int:event_id>/ideas/<int:idea_id>/", UpvoteIdeaView.as_view(), name="upvote-idea"),
]

hackogi/urls.py
from django.contrib import admin
from django.urls import path, include

from hackogi.views import home_page

urlpatterns = [
    path("", home_page, name="home"),
    path("events/", include("events.urls", namespace="events")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_page)
]

events/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from common.models import BaseModel


class Event(BaseModel):
    organizer = models.ForeignKey(
        "accounts.CustomUser",
        on_delete=models.CASCADE,
        related_name="events",
        related_query_name="event",
    )

    title = models.CharField(_("title"), max_length=255)
    overview = models.TextField(_("overview"))

    start_date = models.DateTimeField(_("start date"))
    end_date = models.DateTimeField(_("end date"))

    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Idea(BaseModel):
    event = models.ForeignKey(
        Event, related_name="ideas", related_query_name="idea", on_delete=models.CASCADE
    )
    owner = models.ForeignKey(
        "accounts.CustomUser",
        related_name="ideas",
        related_query_name="idea",
        on_delete=models.CASCADE,
    )
    title = models.CharField(_("title"), max_length=255)
    overview = models.TextField(_("overview"))

    def __str__(self):
        return self.title


class IdeaUpvote(BaseModel):
    idea = models.ForeignKey(
        Idea,
        related_name="upvotes",
        related_query_name="upvote",
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        "accounts.CustomUser",
        related_name="upvotes",
        related_query_name="upvote",
        on_delete=models.CASCADE,
    )

    class Meta:
        unique_together = ("idea", "user",)

    def __str__(self):
        return f"{self.user} likes {self.idea.title}"

events/forms.py
from django import forms

from events.models import Idea


class CreateIdeaForm(forms.ModelForm):
    class Meta:
        model = Idea
        fields = (
            "title",
            "overview",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Idea Title'
        })
        self.fields['overview'].widget = forms.Textarea(attrs={
           'class': 'form-control',
           'placeholder': 'Idea Overview'
        })

events/views.py
from django.http import JsonResponse, HttpResponseNotFound
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Exists, OuterRef
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views import View

from events.forms import CreateIdeaForm
from events.models import Event, Idea, IdeaUpvote


class EventDetailView(View):
    def get(self, request, event_id):
        try:
            event = Event.objects.get(pk=event_id)
        except Event.DoesNotExist:
            return HttpResponse("Event does not exist")

        ideas = event.ideas.annotate(
            is_liked=Exists(
                IdeaUpvote.objects.filter(user=request.user, idea=OuterRef("pk"))
            )
        )
        context = {"event": event, "idea_form": CreateIdeaForm(), "ideas": ideas}

        return render(request, "events/event_detail.html", context=context)


class CreateEventIdeaView(LoginRequiredMixin, View):
    def post(self, request, event_id):
        try:
            event = Event.objects.get(pk=event_id)
        except Event.DoesNotExist:
            return HttpResponse("Event does not exist")

        form = CreateIdeaForm(request.POST)

        if form.is_valid():
            Idea.objects.create(
                owner=request.user,
                event=event,
                title=form.cleaned_data["title"],
                overview=form.cleaned_data["overview"],
            )

        return redirect("events:event-detail", event_id=event.id)


class UpvoteIdeaView(LoginRequiredMixin, View):
    def post(self, request, event_id, idea_id):
        try:
            idea = Idea.objects.get(id=idea_id, event__id=event_id)
        except Idea.DoesNotExist:
            return HttpResponseNotFound("Idea does not exist")

        # Check if the user has already upvoted this idea
        if IdeaUpvote.objects.filter(idea=idea, user=request.user).exists():
            # Optionally, you might want to handle the case where the user tries to upvote again.
            return JsonResponse({'error': 'Already upvoted'}, status=400)

        # Create a new upvote record
        IdeaUpvote.objects.create(idea=idea, user=request.user)

        # Count the number of upvotes for the idea
        upvotes_count = IdeaUpvote.objects.filter(idea=idea).count()

        # Return JSON response with updated like status and count
        return JsonResponse({
            'is_liked': True,
            'upvotes_count': upvotes_count,
        })

events/templates/events/event_detail.html
{% extends 'base.html' %}
{% block title %} Event Detail Page {% endblock title %}

{% block content %}
<style>
    .event-card {
        top: 15px;
        right: 20px;
    }
</style>
<div class="mt-4">
    <div class="d-xl-flex col-xl">
        <div>
            <img src="https://thumbs.dreamstime.com/b/simple-website-html-code-colourful-tags-browser-view-dark-background-orange-text-183366184.jpg"
                class="rounded mx-auto d-block" width="300" alt="***">
        </div>
        <div class="col align-content-end flex-wrap text-center text-xl-start ms-3">
            <h1>{{ event.title }}</h1>
            <nav>
                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab"
                        data-bs-target="#nav-overview" type="button" role="tab" aria-controls="nav-overview"
                        aria-selected="true">Overview</button>
                    <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-ideas"
                        type="button" role="tab" aria-controls="nav-ideas" aria-selected="false">Ideas</button>
                    <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact"
                        type="button" role="tab" aria-controls="nav-contact" aria-selected="false">****</button>
                </div>
            </nav>
        </div>
    </div>

    <div class="tab-content mt-4" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-overview" role="tabpanel" aria-labelledby="nav-overview-tab">
            {{ event.overview }}
        </div>
        <div class="tab-pane fade" id="nav-ideas" role="tabpanel" aria-labelledby="nav-ideas-tab">
            {% if request.user.is_authenticated %}
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary mb-2" data-bs-toggle="modal" data-bs-target="#createIdeas">
                Create Idea
            </button>

            <!-- Modal -->
            <div class="modal fade" id="createIdeas" tabindex="-1" aria-labelledby="createIdeas" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="createIdeas">Create Idea</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <form method="post" action="{% url 'events:create-idea' event.id %}">
                            <div class="modal-body">
                                {% csrf_token %}
                                {{ idea_form.as_p }}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            {% endif %}

            <div class="row gy-4">
                {% for idea in ideas %}
                <div class="col-6">
                    <div class="card">
                        <div class="card-body position-relative">
                            <h5 class="card-title">{{ idea.title }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ idea.overview }}</h6>
                            <div class="position-absolute event-card">
                                <button class="btn btn-link position-relative"
                                    onclick="upvoteIdea('{{ event.id }}', '{{ idea.id }}', this)">
                                    {% if idea.is_liked %}
                                    <i class="fa-solid fa-heart"></i>
                                    {% else %}
                                    <i class="fa-regular fa-heart"></i>
                                    {% endif %}
                                    <span
                                        class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-secondary">
                                        {{ idea.upvotes.count }}
                                        <span class="visually-hidden">unread messages</span>
                                    </span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">...</div>
    </div>

</div>
<script>
    function upvoteIdea(eventId, ideaId, buttonElement) {
        const csrftoken = '{{ csrf_token }}';
        fetch(`/events/${eventId}/ideas/${ideaId}/`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken,
            },
            body: JSON.stringify({}),
        })
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok ' + response.statusText);
                }
                return response.json();
            })
            .then(data => {

                // Update the UI based on the response
                const icon = buttonElement.querySelector('i');
                const badge = buttonElement.querySelector('.badge');

                if (data.is_liked) {
                    icon.classList.remove('fa-regular');
                    icon.classList.add('fa-solid');
                } 

                badge.textContent = data.upvotes_count;
            })
            .catch(error => {
                console.error('There was a problem with your fetch operation:', error);
            });
    }

</script>
{% endblock %}